"""Adiciona campos de perfil do usuário

Revision ID: 7715a2855bd3
Revises: b2faa776d344
Create Date: 2025-11-03 12:01:06.120674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7715a2855bd3'
down_revision = 'b2faa776d344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bloco', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('apartamento', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('apartamento')
        batch_op.drop_column('bloco')
        batch_op.drop_column('telefone')
        batch_op.drop_column('data_nascimento')

    # ### end Alembic commands ###
